apiVersion: 1
datasources:
  # ── Datasource 1: Airflow Metadata DB ─────────────────────────────
  - name: airflow_metadata
    uid: airflow-db
    type: postgres
    url: postgres-airflow:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      database: airflow
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: GET
    isDefault: false
    editable: true

  # ── Datasource 2: Prometheus ───────────────────────────────────────
  - name: prometheus
    uid: prometheus-ptit
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: GET
