apiVersion: 1
datasources:
  - name: school_warehouse
    type: postgres
    url: postgres-warehouse:5432
    database: school_warehouse
    user: warehouse_user
    secureJsonData:
      password: warehouse_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    isDefault: true
    editable: true
